package exception;

public class Exceptionex1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
	try {	
 int a=4;
 int b=0;
 int c=a/b;
	}
 //System.out.println("heloo");
 //System.out.println(c);
 /*catch (ArithmeticException ref)
	{
	 System.out.println("exception occured"+" "+ref);
	 
 }*/
	finally {
		System.out.println("exception completed");
	}
	}
}
